apiVersion: v1
kind: Service
metadata:
  name: simple-app-v2-http
  namespace: simple-app
spec:
  selector:
    app: simple-app
    version: v2
    protocol: http
  ports:
    - port: 80
      targetPort: 5678
