apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: simple-app-gateway
  namespace: simple-app
spec:
  selector:
    istio: ingressgateway
  servers:
  - port: 
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - simple-app.127.0.0.1.sslip.io
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: simple-app
  namespace: simple-app
spec:
  hosts:
  - simple-app.127.0.0.1.sslip.io
  gateways:
  - simple-app-gateway
  http:
  # Simple-app-v1 Matches
  - match:
    - uri:
        prefix: /v1/
    route:
    - destination: 
        host: simple-app-v1-http.simple-app.svc.cluster.local
        port: 
          number: 80
  - match:
    - headers:
        version:
          exact: v1
      uri:
        prefix: "/"
      method:
        exact: POST
      ignoreUriCase: true
    route:
    - destination: 
        host: simple-app-v1-http.simple-app.svc.cluster.local
        port: 
          number: 80
  # Simple-app-v2 Matches
  - match:
    - uri:
        prefix: /v2/
    route:
    - destination:
        host: simple-app-v2-http.simple-app.svc.cluster.local
        port: 
          number: 80
  # Default - Simple-app-v2
  - route:
    - destination:
        host: simple-app-v3-http.simple-app.svc.cluster.local
        port: 
          number: 80
